# Practice 3
# Feedfoward Neural Network using PyTorch
A feedforward neural network can be considered as two or more linear regression models stacked on top of one another with a non-linear activation function applied between them.

In [1]:
# Imports
import torch.nn as nn
import numpy as np
import torch

In [2]:
# Input (temp, rainfall, humidity)
X = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70]], dtype='float32')

In [3]:
# Targets (apples, oranges)
y = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119]], dtype='float32')

In [4]:
X = torch.from_numpy(X)
y = torch.from_numpy(y)

## Dataset and DataLoader

We'll create a TensorDataset, which allows access to rows from inputs and targets as tuples. We'll also create a DataLoader, to split the data into batches while training. It also provides other utilities like shuffling and sampling.

In [5]:
# Import tensor dataset & data loader
from torch.utils.data import TensorDataset, DataLoader

In [6]:
# Define dataset
train_ds = TensorDataset(X, y)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]), tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [7]:
# Define data loader
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)
next(iter(train_dl))

[tensor([[ 91.,  88.,  64.],
         [ 87., 134.,  58.],
         [ 69.,  96.,  70.],
         [ 87., 134.,  58.],
         [ 91.,  88.,  64.]]), tensor([[ 81., 101.],
         [119., 133.],
         [103., 119.],
         [119., 133.],
         [ 81., 101.]])]

## Feedforward Using builtin method
To use a feedforward neural network instead of linear regression, we can extend the nn.Module class from PyTorch.

In [8]:
class SimpleNet(nn.Module):
    # Initialize the layers
    def __init__(self):
        super().__init__()
        self.linear1 = nn.Linear(3, 3)
        self.act1 = nn.ReLU() # Activation function
        self.linear2 = nn.Linear(3, 2)
    
    # Perform the computation
    def forward(self, x):
        x = self.linear1(x)
        x = self.act1(x)
        x = self.linear2(x)
        return x

### Now we define the model, optimizer and loss function.

In [10]:
# Define model
model = SimpleNet()

# Define optimizer
opt = torch.optim.SGD(model.parameters(), 1e-5)

# Import nn.functional
import torch.nn.functional as F

# Define loss function
loss_fn = F.mse_loss

### Train the model
We are ready to train the model now. We can define a utility function fit which trains the model for a given number of epochs.

We can apply gradient descent to train the model using the fit function defined earlier for linear regression in practice 2. We copy the function here from practice 2. 

In [11]:
# Define a utility function to train the model
def fit(num_epochs, model, loss_fn, opt):
    for epoch in range(num_epochs):
        for xb,yb in train_dl:
            # Generate predictions
            pred = model(xb)
            loss = loss_fn(pred, yb)
            # Perform gradient descent
            loss.backward()
            opt.step()
            opt.zero_grad()
    print('Training loss: ', loss_fn(model(X), y))

In [12]:
fit(100, model, loss_fn, opt)

Training loss:  tensor(36.5194, grad_fn=<MseLossBackward>)


In [13]:
# Generate predictions
preds = model(X)
preds

tensor([[ 59.5163,  71.5887],
        [ 80.6264,  97.5753],
        [124.1249, 141.1363],
        [ 30.3835,  41.2628],
        [ 93.2514, 111.0954],
        [ 59.5163,  71.5887],
        [ 80.6264,  97.5753],
        [124.1249, 141.1363],
        [ 30.3835,  41.2628],
        [ 93.2514, 111.0954],
        [ 59.5163,  71.5887],
        [ 80.6264,  97.5753],
        [124.1249, 141.1363],
        [ 30.3835,  41.2628],
        [ 93.2514, 111.0954]], grad_fn=<AddmmBackward>)

In [14]:
# Compare with targets
y

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

This practice is adapted from

https://www.kaggle.com/aakashns/pytorch-basics-linear-regression-from-scratch