# Practice 2
# Linear Regression using PyTorch
##### Here we practice a basic Linear Regression using PyTorch's builtin methods and functions 

In [7]:
# Imports
import torch.nn as nn
import numpy as np
import torch

In [4]:
# Input (temp, rainfall, humidity)
X = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70]], dtype='float32')

In [5]:
# Targets (apples, oranges)
y = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119]], dtype='float32')

In [9]:
X = torch.from_numpy(X)
y = torch.from_numpy(y)

## Dataset and DataLoader

We'll create a TensorDataset, which allows access to rows from inputs and targets as tuples. We'll also create a DataLoader, to split the data into batches while training. It also provides other utilities like shuffling and sampling.

In [10]:
# Import tensor dataset & data loader
from torch.utils.data import TensorDataset, DataLoader

In [11]:
# Define dataset
train_ds = TensorDataset(X, y)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]), tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [12]:
# Define data loader
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)
next(iter(train_dl))

[tensor([[ 73.,  67.,  43.],
         [ 69.,  96.,  70.],
         [ 87., 134.,  58.],
         [ 69.,  96.,  70.],
         [102.,  43.,  37.]]), tensor([[ 56.,  70.],
         [103., 119.],
         [119., 133.],
         [103., 119.],
         [ 22.,  37.]])]

### nn.Linear
Instead of initializing the weights & biases manually, we can define the model using nn.Linear.

In [14]:
# Define model
model = nn.Linear(3, 2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[ 0.2973, -0.1526, -0.4820],
        [ 0.5305, -0.4181,  0.4054]], requires_grad=True)
Parameter containing:
tensor([ 0.3795, -0.2727], requires_grad=True)


### Optimizer
Instead of manually manipulating the weights & biases using gradients, we can use the optimizer optim.SGD.

In [15]:
# Define optimizer
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

### Loss Function
Instead of defining a loss function manually, we can use the built-in loss function mse_loss.

In [16]:
# Import nn.functional
import torch.nn.functional as F

In [17]:
# Define loss function
loss_fn = F.mse_loss

In [20]:
preds = model(X)
loss = loss_fn(preds, y)
print(loss)

tensor(8025.6855, grad_fn=<MseLossBackward>)


### Train the model
We are ready to train the model now. We can define a utility function fit which trains the model for a given number of epochs.

In [24]:
# Define a utility function to train the model
def fit(num_epochs, model, loss_fn, opt):
    for epoch in range(num_epochs):
        for xb,yb in train_dl:
            # Generate predictions
            pred = model(xb)
            loss = loss_fn(pred, yb)
            # Perform gradient descent
            loss.backward()
            opt.step()
            opt.zero_grad()
    print('Training loss: ', loss_fn(model(X), y))

In [25]:
# Train the model for 100 epochs
fit(100, model, loss_fn, opt)

Training loss:  tensor(12.6394, grad_fn=<MseLossBackward>)


In [26]:
# Generate predictions
preds = model(X)
preds

tensor([[ 57.8980,  70.6203],
        [ 79.1105, 100.1068],
        [124.9297, 133.8474],
        [ 24.3158,  38.9290],
        [ 94.6941, 116.9785],
        [ 57.8980,  70.6203],
        [ 79.1105, 100.1068],
        [124.9297, 133.8474],
        [ 24.3158,  38.9290],
        [ 94.6941, 116.9785],
        [ 57.8980,  70.6203],
        [ 79.1105, 100.1068],
        [124.9297, 133.8474],
        [ 24.3158,  38.9290],
        [ 94.6941, 116.9785]], grad_fn=<AddmmBackward>)

In [28]:
# Compare with targets
y

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

This practice is adapted from

https://www.kaggle.com/aakashns/pytorch-basics-linear-regression-from-scratch